version: '3'
services:
  grafana:
    container_name: "grafana"
    image: "ppresto/grafana:1.0"
    environment:
      GF_SECURITY_ADMIN_USER: "consul"
      GF_SECURITY_ADMIN_PASSWORD: "consul"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
    ports:
    - "3000:3000"
