{
 "title": "Consul Monitoring",
 "description": "Get performance metrics from Consul metrics prometheus endpoint /agent/metrics?format=prometheus. Tested with Consul 1.4.4, Prometheus 2.10.0 and Grafana 6.2.4. Although can potentially work with other versions.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "consul",
    "label": "Consul Cluster",
    "query": "label_values(consul_memberlist_gossip_sum, instance)"
   },
   {
    "name": "leader",
    "label": "Leader",
    "query": "label_values(consul_raft_state_leader, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "description": "Tracks the overall health of the local server cluster. If all servers are considered healthy by autopilot, this will be set to 1. If any are unhealthy, this will be 0.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "consul_autopilot_healthy{instance=\"$leader\"}",
     "legendFormat": "consul_autopilot_healthy"
    }
   ]
  },
  {
   "title": "# SERVERS IN CLUSTER",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "COUNT (changes(consul_memberlist_gossip_sum[1m]) > 0) BY (labels)",
     "legendFormat": "$leader"
    }
   ]
  },
  {
   "title": "Raft Health",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "consul_raft_leader_lastContact{instance=\"$leader\", quantile=\"0.5\"}",
     "legendFormat": "lastContractTime {{query}} - {{quantile}}%"
    },
    {
     "expr": "rate(consul_raft_state_candidate{instance=\"$leader\"}[1h])",
     "legendFormat": "new_election"
    },
    {
     "expr": "rate(consul_raft_state_leader{instance=\"$leader\"}[1h])",
     "legendFormat": "new_leader"
    }
   ]
  },
  {
   "title": "Raft Write logs",
   "type": "graph",
   "description": "This measures the time it takes for the leader to write log entries to disk.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "consul_raft_leader_dispatchLog", "legendFormat": "{{quantile}}%" }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Is it running at all?",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n  (\n    sum without() (up{instance=\"$consul\"})\n      or\n    (0 * sum_over_time(up{instance=\"$consul\"}[7d]))\n  )[7d:5m]\n)"
    }
   ]
  },
  {
   "title": "FAILURE TOLERANCE",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "consul_autopilot_failure_tolerance",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Raft Performance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(consul_raft_commitTime{instance=\"$leader\",quantile=\"0.5\"}[1m])",
     "legendFormat": "commit_time"
    }
   ]
  },
  {
   "title": "Raft Commit Count",
   "type": "graph",
   "description": "This counts the number of Raft transactions occurring over the interval, which is a general indicator of the write load on the Consul servers.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "commits/min" }
   ],
   "targets": [
    {
     "expr": "rate(consul_raft_apply{instance=\"$leader\"}[1m])",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "System Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(process_cpu_seconds_total{instance=\"$consul\"}[1m]))",
       "legendFormat": "Consul Process %"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "description": "This measures the number of bytes allocated by the Consul process. Consul keeps all of its data in memory. If Consul consumes all available memory, it will crash.",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "consul_runtime_alloc_bytes{instance=\"$consul\"}",
       "legendFormat": "consul_runtime_alloc_bytes"
      },
      {
       "expr": "avg_over_time(consul_runtime_sys_bytes{instance=\"$consul\"}[5m])",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Memory GC",
     "type": "graph",
     "description": "GC pause is a \"stop-the-world\" event, meaning that all runtime threads are blocked until GC completes. Normally these pauses last only a few nanoseconds. But if memory usage is high, the Go runtime may GC so frequently that it starts to slow down Consul.\nWarning if total_gc_pause_ns exceeds 2 seconds/minute, critical if it exceeds 5 seconds/minute.",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "yaxes": [
      { "format": "ns" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(consul_runtime_gc_pause_ns{instance=\"$consul\",quantile=~\"(0.5|0.99)\"}[5m])",
       "legendFormat": "{{quantile}}%"
      },
      {
       "expr": "delta(consul_runtime_total_gc_runs{instance=\"$consul\"}[5m])",
       "legendFormat": "gc_5m_delta"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_threads{instance=\"$consul\"}"
      },
      {
       "expr": "consul_runtime_num_goroutines{instance=\"$consul\"}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_max_fds{instance=\"$consul\"}"
      },
      {
       "expr": "process_open_fds{instance=\"$consul\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(consul_rpc_query{instance=\"$consul\"}[30s])",
       "legendFormat": "Requests"
      }
     ]
    },
    {
     "title": "TCP Messages",
     "type": "graph",
     "description": "The amount of TCP messages that are sent/received from the server.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(consul_memberlist_tcp_connect{instance=\"$consul\"}[1m])",
       "legendFormat": "connect"
      },
      {
       "expr": "irate(consul_memberlist_tcp_sent{instance=\"$consul\"}[1m])",
       "legendFormat": "sent"
      },
      {
       "expr": "irate(consul_memberlist_tcp_accept{instance=\"$consul\"}[1m])",
       "legendFormat": "accept"
      }
     ]
    },
    {
     "title": "UDP Messages",
     "type": "graph",
     "description": "The amount of UDP messages in bytes that are sent/received from the server.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "irate(consul_memberlist_udp_sent{instance=\"$consul\"}[1m])",
       "legendFormat": "sent"
      },
      {
       "expr": "irate(consul_memberlist_udp_received{instance=\"$consul\"}[1m])",
       "legendFormat": "received"
      }
     ]
    },
    {
     "title": "Serf Coordinates",
     "type": "graph",
     "description": "Consul uses a network tomography system to compute network coordinates for nodes in the cluster. These coordinates allow the network round trip time to be estimated between any two nodes using a very simple calculation. This allows for many useful applications, such as finding the service node nearest a requesting node, or failing over to services in the next closest datacenter.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_serf_coordinate_adjustment_ms{instance=\"$consul\"}",
       "legendFormat": "{{quantile}}%"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Domain Query Time",
     "type": "graph",
     "description": "Shows the time spent handling a domain queries for each node. A spike here may indicate that there are too many concurrent domain queries, or the catalog is under high contention.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "yaxes": [
      { "format": "dtdurationms" }
     ],
     "targets": [
      {
       "expr": "consul_dns_domain_query{instance=\"$consul\", quantile=\"0.9\"}"
      }
     ]
    },
    {
     "title": "DNS Queries per 5m",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(consul_dns_domain_query_count{instance=\"$consul\"}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "ACL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "ACL Resolves per 5min",
     "type": "graph",
     "description": "Counts how many ACL tokens are resolved and buckets them by 5 minute intervals. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops/5m" } },
     "yaxes": [
      { "format": "ops/5m" }
     ],
     "targets": [
      {
       "expr": "rate(consul_acl_ResolveToken_count{instance=\"$consul\"}[5m])"
      }
     ]
    },
    {
     "title": "ACL ResolveToken Time",
     "type": "graph",
     "description": "Times how long it takes to resolve an ACL Token into its policies.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "consul_acl_ResolveToken{instance=\"$consul\"}"
      }
     ]
    },
    {
     "title": "ACL Updates per 5m",
     "type": "graph",
     "description": "This counts the number of times we've updated an ACL, bucketed into 5 minute intervals.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ops/5m" } },
     "yaxes": [
      { "format": "ops/5m" }
     ],
     "targets": [
      {
       "expr": "rate(consul_acl_policy_upsert_count{instance=\"$consul\"}[5m])"
      }
     ]
    },
    {
     "title": "ACL Apply Time",
     "type": "graph",
     "description": "This measures the time it takes to complete an update to the ACL store.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "consul_acl_policy_upsert" }
     ]
    }
   ]
  },
  {
   "title": "Catalog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Catalog Operations per 5m",
     "type": "graph",
     "description": "This shows the rate of increase for catalog register and deregister operations. ",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ops/5m" } },
     "yaxes": [
      { "format": "ops/5m" }
     ],
     "targets": [
      {
       "expr": "rate(consul_catalog_register_count[1m])"
      }
     ]
    },
    {
     "title": "Catalog Operation Time",
     "type": "graph",
     "description": "Measures the time it takes to complete catalog register or deregister operations.",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "consul_catalog_register" }
     ]
    }
   ]
  },
  {
   "title": "KV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Applies per 5m",
     "type": "graph",
     "description": "Shows the rate of KV operations in 5 minute buckets. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ops/5m" } },
     "yaxes": [
      { "format": "ops/5m" }
     ],
     "targets": [
      {
       "expr": "rate(consul_kvs_apply_count[5m])"
      }
     ]
    },
    {
     "title": "KV Apply Time",
     "type": "graph",
     "description": "This measures the time it takes to complete an update to the KV store.\n\nNOTE: If there are too many timeseries here from clients, consider filtering down to server hosts. You can set this with a prometheus scrape target based on the node's role.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      { "expr": "consul_kvs_apply" }
     ]
    },
    {
     "title": "Log replication from leader to servers",
     "type": "graph",
     "description": "This measures the time it takes to replicate log entries to followers. This is a general indicator of the load pressure on the Consul servers, as well as the performance of the communication between the servers.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"consul_raft_replication_appendEntries_rpc_.*sum\"}"
      }
     ]
    }
   ]
  }
 ]
}