{
 "title": "Locust",
 "description": "Locust Exporter - Container Solutions",
 "tags": [ "locust" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Hashicups",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    { "expr": "locust_running" }
   ]
  },
  {
   "title": "Avg Response Time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "locust_requests_avg_response_time{name=\"Aggregated\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Failures/sec",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "locust_requests_current_fail_per_sec{name=\"Aggregated\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Users",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "locust_users", "legendFormat": " " }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(locust_requests_current_rps{name=\"Aggregated\"})",
     "legendFormat": "Reqs/sec"
    },
    {
     "expr": "sum(locust_requests_current_fail_per_sec{name=\"Aggregated\"})",
     "legendFormat": "Failures/sec"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "P95"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(locust_requests_max_response_time)",
     "legendFormat": "AVG MAX"
    },
    {
     "expr": "avg(locust_requests_min_response_time)",
     "legendFormat": "AVG MIN"
    },
    {
     "expr": "avg(locust_requests_avg_response_time)",
     "legendFormat": "AVG AVG"
    },
    {
     "expr": "avg(locust_requests_median_response_time)",
     "legendFormat": "AVG MEDIAN"
    }
   ]
  },
  {
   "title": "Requests per endpoint / s",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(locust_requests_num_requests{method=~\".+\"}[1m])",
     "legendFormat": "{{ method}} - {{name}}"
    },
    {
     "expr": " sum(rate(locust_requests_num_requests{method=~\".+\"}[1m]))",
     "legendFormat": "total"
    },
    {
     "expr": "locust_requests_fail_ratio * 100",
     "legendFormat": "fail_ratio [%]"
    }
   ]
  }
 ]
}